spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tourist??useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1102
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true